# Generated by Django 4.0.3 on 2022-08-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('regtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('user_status', models.CharField(default='正常', max_length=32, verbose_name='用户状态')),
                ('user_level', models.IntegerField(default=1, verbose_name='用户等级')),
            ],
        ),
    ]
