# Generated by Django 4.0.3 on 2023-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('uid', models.CharField(max_length=32, verbose_name='用户id')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='昵称')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='用户手机')),
                ('level', models.IntegerField(default=1, verbose_name='用户等级')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
