# Generated by Django 4.0.3 on 2024-02-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usermodel_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='img',
            field=models.CharField(default='', max_length=128, verbose_name='用户头像'),
        ),
    ]
