# Generated by Django 4.0.3 on 2024-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_usermodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('username', models.CharField(max_length=32, verbose_name='用户账号')),
                ('file_name', models.CharField(default='', max_length=255, verbose_name='图片名称')),
                ('mid_raw', models.CharField(max_length=64, verbose_name='图片id原图')),
                ('mid_handle', models.CharField(max_length=64, verbose_name='图片id检测后的图')),
                ('path_raw', models.CharField(max_length=128, verbose_name='原图路径')),
                ('path_handle', models.CharField(max_length=128, verbose_name='处理后图片路径')),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(max_length=64, verbose_name='用户id'),
        ),
    ]
