# Generated by Django 4.0.3 on 2024-03-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_imgmodel_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='mid_handle',
            field=models.CharField(default='', max_length=64, verbose_name='图片id检测后的图'),
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='path_handle',
            field=models.CharField(default='', max_length=128, verbose_name='处理后图片路径'),
        ),
    ]
