# Generated by Django 4.0.3 on 2024-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_imgmodel_mid_handle_alter_imgmodel_path_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmodel',
            name='item',
            field=models.CharField(default='', max_length=128, verbose_name='分类'),
        ),
    ]
