# Generated by Django 4.0.3 on 2025-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_imgmodel_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('username', models.CharField(max_length=64, verbose_name='用户账号')),
                ('file_name', models.CharField(default='', max_length=255, verbose_name='文件名称')),
                ('mid_raw', models.CharField(max_length=64, verbose_name='原文件地址')),
                ('mid_handle', models.CharField(default='', max_length=64, verbose_name='检测后的文件地址')),
                ('path_raw', models.CharField(max_length=128, verbose_name='原文件地址')),
                ('path_handle', models.CharField(default='', max_length=128, verbose_name='处理后文件地址')),
                ('item', models.CharField(default='', max_length=128, verbose_name='分类')),
            ],
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='username',
            field=models.CharField(max_length=64, verbose_name='用户账号'),
        ),
    ]
