# Generated by Django 5.1.7 on 2025-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_videomodel_alter_imgmodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAddAskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('uid', models.CharField(max_length=64, verbose_name='用户id')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('describe', models.CharField(max_length=255, verbose_name='说明')),
                ('source', models.CharField(max_length=255, verbose_name='数据集来源')),
                ('state', models.CharField(max_length=32, verbose_name='状态')),
                ('admin_reply', models.CharField(max_length=255, verbose_name='管理员回复')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('username', models.CharField(max_length=64, verbose_name='用户账号')),
                ('uid', models.CharField(max_length=64, verbose_name='用户id')),
                ('model', models.CharField(max_length=128, verbose_name='模型')),
                ('files_name', models.CharField(max_length=128, verbose_name='文件夹')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件')),
                ('slice_count', models.IntegerField(verbose_name='范围')),
                ('mid_handle', models.CharField(default='', max_length=64, verbose_name='检测后的图片id')),
                ('path_handle', models.CharField(default='', max_length=128, verbose_name='检测后图片路径')),
            ],
        ),
        migrations.DeleteModel(
            name='ImgModel',
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
